# Market Symbols Configuration
# This file contains the list of futures and equities to track

futures:
  - symbol: ES
    description: "E-mini S&P 500 Futures"
    type: Futures
    update_frequency: daily
    start_date: "2003-01-01"
    exchange: CME
    contract_size: 50
    tick_size: 0.25
    tick_value: 12.50
    contract_months: ['H', 'M', 'U', 'Z']  # Mar, Jun, Sep, Dec

equities:
  # Major ETFs
  - symbol: SPY
    description: "SPDR S&P 500 ETF"
    type: ETF
    update_frequency: daily
    start_date: "2023-01-01"
    
  - symbol: QQQ
    description: "Invesco QQQ Trust"
    type: ETF
    update_frequency: daily
    start_date: "2023-01-01"
    

settings:
  default_update_frequency: daily
  retry_attempts: 3
  cache_duration: 24h  # How long to cache the data
  price_types:
    - Open
    - High
    - Low
    - Close
    - Volume
