# futures.yaml
# Configuration for futures contracts with their specifications, roll rules, and exchange mappings

version: "1.0"

# Common templates for futures to reduce repetition
templates:
  equity_index_futures:
    default_source: "tradestation"
    default_raw_table: "market_data"
    frequencies: ["1min", "15min", "daily"]
    roll_method: "volume"
    expiry_rule:
      rule:
        nth_weekday:
          n: 3
          weekday: "friday"
      calendar: "CME_Equity"
    tick_size: 0.25
    tick_value: 12.50
    
  vix_futures:
    default_source: "tradestation"
    default_raw_table: "market_data"
    frequencies: ["1min", "15min", "daily"]
    roll_method: "volume"
    expiry_rule:
      special_rule: "VX_expiry"
    tick_size: 0.05
    tick_value: 50.00
  
  energy_futures:
    default_source: "tradestation"
    default_raw_table: "market_data"
    frequencies: ["1min", "15min", "daily"]
    roll_method: "volume"
    expiry_rule:
      rule:
        business_days_before_day_of_month:
          days_before: 3
          day_of_month: 25
      calendar: "CMEGlobex_CL"
      
  metal_futures:
    default_source: "tradestation"
    default_raw_table: "market_data"
    frequencies: ["daily"]
    roll_method: "volume"
    expiry_rule:
      rule:
        business_days_before_last_bday_of_month:
          days_before: 3
      calendar: "CMEGlobex_GC"

# Futures contract specifications
futures:
  ES:
    inherit: "equity_index_futures"
    name: "E-mini S&P 500 Futures"
    description: "E-mini S&P 500 Futures"
    asset_class: "equity_index"
    exchange: "CME"
    exchange_ref: "${exchanges.CME}"
    currency: "USD"
    calendar: "CME_Equity"
    calendar_ref: "${exchanges.CME.calendars.CME_Equity}"
    contract_info:
      patterns: ["H", "M", "U", "Z"]
      start_year: 2003
      num_active_contracts: 2
    continuous_contracts:
      - identifier: "@ES=102XN"
        description: "ES Continuous Contract (Unadjusted, TradeStation)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2003-01-01"
        default_source: "tradestation"
      - identifier: "@ES=102XN_d"
        description: "ES Continuous Contract (Unadjusted, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2003-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@ES=102XN"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "N"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_unadj_2day_1pos_d"
      - identifier: "@ES=102XC"
        description: "ES Continuous Contract (Adjusted, Backward Constant, TradeStation)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2003-01-01"
        default_source: "tradestation"
      - identifier: "@ES=102XC_d"
        description: "ES Continuous Contract (Adjusted, Backward Constant, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2003-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@ES=102XC"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "C"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_adj_const_2day_1pos_d"

  NQ:
    inherit: "equity_index_futures"
    name: "E-mini NASDAQ-100 Futures"
    description: "E-mini NASDAQ-100 Futures"
    asset_class: "equity_index"
    exchange: "CME"
    exchange_ref: "${exchanges.CME}"
    currency: "USD"
    calendar: "CME_Equity"
    calendar_ref: "${exchanges.CME.calendars.CME_Equity}"
    multiplier: 20
    point_value: 20.00
    settlement_type: "cash"
    contract_info:
      patterns: ["H", "M", "U", "Z"]
      start_year: 2003
      num_active_contracts: 2
    continuous_contracts:
      - identifier: "@NQ=102XN"
        description: "NQ Continuous Contract (Unadjusted, TradeStation)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2003-01-01"
        default_source: "tradestation"
      - identifier: "@NQ=102XN_d"
        description: "NQ Continuous Contract (Unadjusted, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2003-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@NQ=102XN"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "N"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_unadj_2day_1pos_d"
      - identifier: "@NQ=102XC"
        description: "NQ Continuous Contract (Adjusted, Backward Constant, TradeStation)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2003-01-01"
        default_source: "tradestation"
      - identifier: "@NQ=102XC_d"
        description: "NQ Continuous Contract (Adjusted, Backward Constant, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2003-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@NQ=102XC"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "C"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_adj_const_2day_1pos_d"

  CL:
    inherit: "energy_futures"
    name: "Crude Oil Futures"
    description: "Crude Oil Futures"
    asset_class: "energy"
    exchange: "NYMEX"
    exchange_ref: "${exchanges.NYMEX}"
    currency: "USD"
    calendar: "CMEGlobex_CL"
    calendar_ref: "${exchanges.NYMEX.calendars.CMEGlobex_CL}"
    multiplier: 1000
    point_value: 1000.00
    tick_size: 0.01
    tick_value: 10.00
    settlement_type: "physical"
    contract_info:
      patterns: ["F", "G", "H", "J", "K", "M", "N", "Q", "U", "V", "X", "Z"]
      start_year: 2005
      start_month: 6
      num_active_contracts: 6
    continuous_contracts:
      - identifier: "@CL=102XN"
        description: "CL Continuous Contract (Unadjusted, TradeStation)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["daily"]
        start_date: "2005-01-01"
        default_source: "tradestation"
      - identifier: "@CL=102XN_d"
        description: "CL Continuous Contract (Unadjusted, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["daily"]
        start_date: "2005-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@CL=102XN"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "N"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_unadj_2day_1pos_d"
      - identifier: "@CL=102XC"
        description: "CL Continuous Contract (Adjusted, Backward Constant, TradeStation)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["daily"]
        start_date: "2005-01-01"
        default_source: "tradestation"
      - identifier: "@CL=102XC_d"
        description: "CL Continuous Contract (Adjusted, Backward Constant, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["daily"]
        start_date: "2005-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@CL=102XC"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "C"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_adj_const_2day_1pos_d"

  GC:
    inherit: "metal_futures"
    name: "Gold Futures"
    description: "Gold Futures"
    asset_class: "metals"
    exchange: "COMEX"
    exchange_ref: "${exchanges.COMEX}"
    currency: "USD"
    calendar: "CMEGlobex_GC"
    calendar_ref: "${exchanges.COMEX.calendars.CMEGlobex_GC}"
    multiplier: 100
    point_value: 100.00
    tick_size: 0.10
    tick_value: 10.00
    settlement_type: "physical"
    contract_info:
      patterns: ["G", "J", "M", "Q", "V", "Z"]
      start_year: 2004
      num_active_contracts: 6
    continuous_contracts:
      - identifier: "@GC=102XN"
        description: "GC Continuous Contract (Unadjusted, TradeStation)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["daily"]
        start_date: "2004-01-01"
        default_source: "tradestation"
      - identifier: "@GC=102XN_d"
        description: "GC Continuous Contract (Unadjusted, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["daily"]
        start_date: "2004-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@GC=102XN"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "N"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_unadj_2day_1pos_d"
      - identifier: "@GC=102XC"
        description: "GC Continuous Contract (Adjusted, Backward Constant, TradeStation)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["daily"]
        start_date: "2004-01-01"
        default_source: "tradestation"
      - identifier: "@GC=102XC_d"
        description: "GC Continuous Contract (Adjusted, Backward Constant, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["daily"]
        start_date: "2004-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@GC=102XC"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "C"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_adj_const_2day_1pos_d"

  VX:
    inherit: "vix_futures"
    name: "CBOE Volatility Index Futures"
    description: "CBOE Volatility Index Futures"
    asset_class: "volatility"
    exchange: "CBOE"
    exchange_ref: "${exchanges.CBOE}"
    currency: "USD"
    calendar: "CFE"
    calendar_ref: "${exchanges.CBOE.calendars.CFE}"
    multiplier: 1000
    point_value: 1000.00
    settlement_type: "cash"
    contract_info:
      patterns: ["F", "G", "H", "J", "K", "M", "N", "Q", "U", "V", "X", "Z"]
      start_year: 2006
      num_active_contracts: 9
    continuous_contracts:
      - identifier: "@VX=102XN"
        description: "VX Continuous Contract (Unadjusted, TradeStation)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2006-01-01"
        default_source: "tradestation"
      - identifier: "@VX=102XN_d"
        description: "VX Continuous Contract (Unadjusted, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "none"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2006-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@VX=102XN"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "N"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_unadj_2day_1pos_d"
      - identifier: "@VX=102XC"
        description: "VX Continuous Contract (Adjusted, Backward Constant, TradeStation)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2006-01-01"
        default_source: "tradestation"
      - identifier: "@VX=102XC_d"
        description: "VX Continuous Contract (Adjusted, Backward Constant, In-house Built, 2-day Roll)"
        type: "continuous_future"
        method: "backwards_constant"
        position: 1
        frequencies: ["15min", "daily"]
        start_date: "2006-01-01"
        default_source: "inhouse_built"
        base_contract_for_build: "@VX=102XC"
        build_roll_type: "02X"
        build_contract_position: 1
        build_adjustment_type: "C"
        build_output_symbol_suffix: "_d"
        build_source_identifier: "inhouse_adj_const_2day_1pos_d"
    continuous_contract_group:
      identifier_base: "@VX"
      month_codes: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
      settings_code: "01XN"
      description_template: "TradeStation Continuous VIX Future ({nth_month} month)"
      type: "continuous_future"
      frequencies: ["daily"]
      start_date: "2005-01-01"

# Expiry calculation rules
expiry_rules:
  VX_expiry:
    description: "VIX futures expire 30 days before the 3rd Friday of the following month"
    calculation:
      base: "nth_weekday"
      parameters:
        nth: 3
        weekday: "Friday"
        month: "following"
      offset: -30
      offset_units: "days"
      adjust_for_holiday: true

# Exchange and Calendar Definitions (ensure these are complete and correct)
# This section is illustrative; your actual definitions might be more detailed
exchanges:
  CME: