equities:
  - symbol: SPY
    description: SPDR S&P 500 ETF
    exchange: NYSE
    type: ETF
    frequencies:
      - 1min
      - 15min
      - daily
  - symbol: QQQ
    description: Invesco QQQ Trust
    exchange: NASDAQ
    type: ETF
    frequencies:
      - 1min
      - 15min
      - daily
  - symbol: AAPL
    description: Apple Inc.
    exchange: NASDAQ
    type: Stock
    frequencies:
      - daily
  - symbol: MSFT
    description: Microsoft Corporation
    exchange: NASDAQ
    type: Stock
    frequencies:
      - daily
  - symbol: GS
    description: Goldman Sachs Group Inc.
    exchange: NYSE
    type: Stock
    frequencies:
      - daily

futures:
  - base_symbol: ES
    calendar: US
    description: E-mini S&P 500 Futures
    exchange: CME
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - H
        - M
        - U
        - Z
      start_month: 1
      start_year: 2003
    num_active_contracts: 2
    expiry_rule:
      day_type: friday
      day_number: 3  # Third Friday
      adjust_for_holiday: true
      holiday_calendar: US
    start_date: '2003-01-01'

  - base_symbol: NQ
    calendar: US
    description: E-mini NASDAQ-100 Futures
    exchange: CME
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - H
        - M
        - U
        - Z
      start_month: 1
      start_year: 2003
    num_active_contracts: 2
    expiry_rule:
      day_type: friday
      day_number: 3  # Third Friday
      adjust_for_holiday: true
      holiday_calendar: US
    start_date: '2003-01-01'

  - base_symbol: CL
    calendar: US
    description: Crude Oil Futures
    exchange: NYMEX
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - F
        - G
        - H
        - J
        - K
        - M
        - N
        - Q
        - U
        - V
        - X
        - Z
      start_month: 1
      start_year: 2004
    num_active_contracts: 12
    expiry_rule:
      day_type: business_day
      days_before: 3  # Three business days before the 25th
      adjust_for_holiday: true
      holiday_calendar: US
    start_date: '2004-01-01'

  - base_symbol: GC
    calendar: US
    description: Gold Futures
    exchange: COMEX
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - G
        - J
        - M
        - Q
        - V
        - Z
      start_month: 1
      start_year: 2004
    num_active_contracts: 6
    expiry_rule:
      day_type: business_day
      days_before: 3  # Three business days before the last business day
      adjust_for_holiday: true
      holiday_calendar: US
    start_date: '2004-01-01'

  - base_symbol: VX
    calendar: US
    description: VIX Futures
    exchange: CBOE
    frequencies:
      - daily
    historical_contracts:
      patterns:
        - F  # February
        - G  # March
        - H  # April
        - J  # May
        - K  # June
        - M  # July
        - N  # August
        - Q  # September
        - U  # October
        - V  # November
        - X  # December
        - Z  # January
      start_month: 1
      start_year: 2004
    num_active_contracts: 9  # Monthly contracts
    expiry_rule:
      day_type: wednesday
      day_number: 3  # Third Wednesday
      adjust_for_holiday: true
      holiday_calendar: US
    start_date: '2004-01-01'

settings:
  data_frequencies:
    - interval: 15  #Earliest 15min data is 2010-01-01
      name: 15min
      unit: minute
    - interval: 1
      name: daily  #Earliest daily data is 2004-03-26
      unit: day
  default_start_date: '2004-03-26'
  holiday_calendar: NYSE
  holidays:
    NYSE:
      fixed_dates:
        - '01-01'  # New Year's Day
        - '06-19'  # Juneteenth
        - '07-04'  # Independence Day
        - '12-25'  # Christmas Day
      relative_dates:
        - name: "Martin Luther King Jr. Day"
          month: 1
          day_type: "monday"
          occurrence: 3  # Third Monday
        - name: "Presidents Day"
          month: 2
          day_type: "monday"
          occurrence: 3  # Third Monday
        - name: "Good Friday"
          month: 4  # This will be calculated based on Easter
          day_type: "friday"
          occurrence: -1  # Last Friday before Easter
        - name: "Memorial Day"
          month: 5
          day_type: "monday"
          occurrence: -1  # Last Monday
        - name: "Labor Day"
          month: 9
          day_type: "monday"
          occurrence: 1  # First Monday
        - name: "Thanksgiving"
          month: 11
          day_type: "thursday"
          occurrence: 4  # Fourth Thursday
