# YAML Configuration for Market Symbols

indices:
  - symbol: $VIX.X
    description: CBOE Volatility Index
    exchange: CBOE
    type: Index
    default_source: tradestation
    default_raw_table: market_data
    frequencies: # Kept as list of dictionaries
      - name: daily # Uses defaults
        interval: 1
        unit: daily
    start_date: '2005-01-01' # Product/data start
    calendar: CFE


futures:
  - base_symbol: ES
    symbol: "@ES" # Symbol for fetching generic continuous data from TradeStation
    asset_type: future_group
    default_source: tradestation # Source for @ES data
    default_raw_table: market_data # Table for @ES data
    calendar: CME_Equity
    description: E-mini S&P 500 Futures (Defaults)
    exchange: CME
    frequencies: [15min, daily] # Frequencies for @ES data
    # Default Product Specifications (can be overridden in futures.yaml)
    start_date: '2003-01-01' # Product start date
    historical_contracts:
      patterns: [H, M, U, Z]
      start_year: 2003
    num_active_contracts: 2
    expiry_rule:
      day_type: friday
      day_number: 3
      adjust_for_holiday: true
    contract_specs:
      multiplier: 50
      point_value: 50.00
      tick_size: 0.25
      tick_value: 12.50
      settlement_type: cash

  - base_symbol: NQ
    symbol: "@NQ"
    asset_type: future_group
    default_source: tradestation
    default_raw_table: market_data
    calendar: CME_Equity
    description: E-mini NASDAQ-100 Futures (Defaults)
    exchange: CME
    frequencies: [15min, daily]
    # Default Product Specifications
    start_date: '2003-01-01'
    historical_contracts:
      patterns: [H, M, U, Z]
      start_year: 2003
    num_active_contracts: 2
    expiry_rule:
      day_type: friday
      day_number: 3
      adjust_for_holiday: true
    contract_specs:
      multiplier: 20 # NQ specific
      point_value: 20.00 # NQ specific
      tick_size: 0.25
      tick_value: 5.00 # NQ specific (0.25 * 20)
      settlement_type: cash

  - base_symbol: CL
    symbol: "@CL"
    asset_type: future_group
    default_source: tradestation
    default_raw_table: market_data
    calendar: CMEGlobex_CL
    description: Crude Oil Futures (Defaults)
    exchange: NYMEX
    frequencies: [15min, daily]
    # Default Product Specifications
    start_date: '2005-01-01'
    historical_contracts:
      patterns: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      start_year: 2005
      start_month: 6
    num_active_contracts: 6
    expiry_rule:
      day_type: business_day
      days_before: 3
      reference_day: 25
      adjust_for_holiday: true
    contract_specs:
      multiplier: 1000
      point_value: 1000.00
      tick_size: 0.01
      tick_value: 10.00
      settlement_type: physical

  - base_symbol: GC
    symbol: "@GC"
    asset_type: future_group
    default_source: tradestation
    default_raw_table: market_data
    calendar: CMEGlobex_GC
    description: Gold Futures (Defaults)
    exchange: COMEX
    frequencies: [daily]
    # Default Product Specifications
    start_date: '2004-01-01'
    historical_contracts:
      patterns: [G, J, M, Q, V, Z]
      start_year: 2004
    num_active_contracts: 6
    expiry_rule:
      day_type: business_day
      days_before: 3
      reference_point: last_business_day
      adjust_for_holiday: true
    contract_specs:
      multiplier: 100
      point_value: 100.00
      tick_size: 0.10
      tick_value: 10.00
      settlement_type: physical

  - base_symbol: VX
    symbol: "@VX"
    asset_type: future_group
    default_source: tradestation # Source for @VX data
    default_raw_table: market_data # Table for @VX data
    calendar: CFE
    description: CBOE Volatility Index Futures (Defaults)
    exchange: CBOE
    frequencies: # Frequencies for @VX data
      - name: daily
        interval: 1
        unit: daily
      - name: 15min
        interval: 15
        unit: minute
    # Default Product Specifications
    start_date: '2004-01-01' # Product start
    historical_contracts:
      patterns: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      start_year: 2004
      exclude_contracts: # From futures.yaml VX block
        - "VXF04"
        - "VXG04"
        - "VXH04"
        - "VXJ04"
        - "VXZ04"
        - "VXJ05"
        - "VXN05"
        - "VXU05"
    num_active_contracts: 9
    expiry_rule:
      day_type: wednesday # Specific to VIX
      special_rule: VX_expiry # Specific to VIX
    contract_specs:
      multiplier: 1000 # VIX specific
      point_value: 1000.00 # VIX specific
      tick_size: 0.05 # VIX specific template
      tick_value: 50.00 # VIX specific template (0.05 * 1000)
      settlement_type: cash

equities:
  - symbol: SPY
    description: SPDR S&P 500 ETF
    exchange: NYSE
    calendar: NYSE # Added calendar
    type: ETF
    default_source: tradestation
    default_raw_table: market_data
    frequencies: [1min, 15min, daily]
    start_date: '2001-01-01'

  - symbol: QQQ
    description: Invesco QQQ Trust
    exchange: NASDAQ
    calendar: NASDAQ # Added calendar
    type: ETF
    default_source: tradestation
    default_raw_table: market_data
    frequencies: [1min, 15min, daily]
    start_date: '2001-01-01'

  - symbol: AAPL
    description: Apple Inc.
    exchange: NASDAQ
    calendar: NASDAQ # Added calendar
    type: Stock
    default_source: tradestation
    default_raw_table: market_data
    frequencies: [daily]
    start_date: '2001-01-01'

  - symbol: GS
    description: Goldman Sachs Group Inc.
    exchange: NYSE
    calendar: NYSE # Added calendar
    type: Stock
    default_source: tradestation
    default_raw_table: market_data
    frequencies: [daily]
    start_date: '2001-01-01'


settings:
  data_frequencies:
    - interval: 15
      name: 15min
      unit: minute
    - interval: 1
      name: daily
      unit: daily
    - interval: 1
      name: 1min
      unit: minute
  default_start_date: '2004-03-26'
