# YAML Configuration for Market Symbols

indices:
  - symbol: $VIX.X
    description: CBOE Volatility Index
    exchange: CBOE
    type: Index
    default_source: tradestation
    default_raw_table: market_data
    frequencies: # Kept as list of dictionaries
      - name: daily # Uses defaults
        interval: 1
        unit: daily
    start_date: '2005-01-01'
    calendar: CFE


futures:
  - base_symbol: ES
    default_source: tradestation
    default_raw_table: market_data
    calendar: CME_Equity
    description: E-mini S&P 500 Futures
    exchange: CME
    frequencies: [1min, 15min, daily] # Reverted to simple list
    historical_contracts:
      patterns: [H, M, U, Z]
      start_year: 2003
    num_active_contracts: 2
    expiry_rule:
      day_type: friday
      day_number: 3
      adjust_for_holiday: true
    start_date: '2003-01-01'

  - base_symbol: NQ
    default_source: tradestation
    default_raw_table: market_data
    calendar: CME_Equity
    description: E-mini NASDAQ-100 Futures
    exchange: CME
    frequencies: [1min, 15min, daily] # Reverted to simple list
    historical_contracts:
      patterns: [H, M, U, Z]
      start_year: 2003
    num_active_contracts: 2
    expiry_rule:
      day_type: friday
      day_number: 3
      adjust_for_holiday: true
    start_date: '2003-01-01'

  - base_symbol: CL
    default_source: tradestation
    default_raw_table: market_data
    calendar: CMEGlobex_CL
    description: Crude Oil Futures
    exchange: NYMEX
    frequencies: [1min, 15min, daily] # Reverted to simple list
    historical_contracts:
      patterns: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      start_year: 2005
      start_month: 6
    num_active_contracts: 12
    expiry_rule:
      day_type: business_day
      days_before: 3
      reference_day: 25
      adjust_for_holiday: true
    start_date: '2005-01-01'

  - base_symbol: GC
    default_source: tradestation
    default_raw_table: market_data
    calendar: CMEGlobex_GC
    description: Gold Futures
    exchange: COMEX
    frequencies: [daily] # Reverted to simple list
    historical_contracts:
      patterns: [G, J, M, Q, V, Z]
      start_year: 2004
    num_active_contracts: 6
    expiry_rule:
      day_type: business_day
      days_before: 3
      reference_point: last_business_day
      adjust_for_holiday: true
    start_date: '2004-01-01'

  - base_symbol: VX
    default_source: tradestation
    default_raw_table: market_data
    calendar: CFE
    description: CBOE Volatility Index Futures
    exchange: CBOE
    frequencies: # MODIFIED - removed CBOE override for daily
      - name: daily
        interval: 1 # Now uses default_source (tradestation) and default_raw_table (market_data)
        unit: daily
      - name: 1min               # Uses defaults
        interval: 1
        unit: minute
      - name: 15min              # Uses defaults
        interval: 15
        unit: minute
    historical_contracts:
      patterns: [F, G, H, J, K, M, N, Q, U, V, X, Z]
      start_year: 2004 # This will be overridden by the symbol-level start_date for fetching, but retain for reference
      exclude_contracts: # Added list of known non-trading contracts
        - VXF04
        - VXG04
        - VXH04
        - VXJ04
        - VXZ04
        - VXJ05
        - VXN05
        - VXU05
    num_active_contracts: 9
    expiry_rule:
      day_type: wednesday
      special_rule: VX_expiry
    start_date: '2005-01-01' # MODIFIED

  # REPLACED: 9 individual @VX=...XN entries with a continuous_group
  - continuous_group:
      identifier_base: "@VX"
      month_codes: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
      settings_code: "01XN"
      description_template: "TradeStation Continuous VIX Future ({nth_month} month)"
      exchange: CFE
      type: continuous_future
      default_source: tradestation
      default_raw_table: market_data
      frequencies: [daily]
      start_date: '2005-01-01'
      calendar: CFE

  - symbol: "@ES=102XC"
    type: continuous_future
    description: "ES Continuous Contract (Adjusted, Backwards Ratio, TradeStation)"
    default_source: tradestation
    exchange: CME
    calendar: CME_Equity
    frequencies: [1min,15min, daily]
    start_date: '2003-01-01'

  - symbol: "@ES=101XN"
    type: continuous_future
    description: "ES Continuous Contract (Unadjusted, TradeStation)"
    default_source: tradestation
    exchange: CME
    calendar: CME_Equity
    frequencies: [1min, 15min, daily]
    start_date: '2003-01-01'

  - symbol: "@NQ=102XC"
    type: continuous_future
    description: "NQ Continuous Contract (Adjusted, Backwards Ratio, TradeStation)"
    default_source: tradestation
    exchange: CME
    calendar: CME_Equity
    frequencies: [1min, 15min, daily]
    start_date: '2003-01-01'

  - symbol: "@NQ=101XN"
    type: continuous_future
    description: "NQ Continuous Contract (Unadjusted, TradeStation)"
    default_source: tradestation
    exchange: CME
    calendar: CME_Equity
    frequencies: [1min, 15min, daily]
    start_date: '2003-01-01'

equities:
  - symbol: SPY
    description: SPDR S&P 500 ETF
    exchange: NYSE
    calendar: NYSE # Added calendar
    type: ETF
    default_source: tradestation
    default_raw_table: market_data
    frequencies: [1min, 15min, daily] # Reverted to simple list
    start_date: '2001-01-01'

  - symbol: QQQ
    description: Invesco QQQ Trust
    exchange: NASDAQ
    calendar: NASDAQ # Added calendar
    type: ETF
    default_source: tradestation
    default_raw_table: market_data
    frequencies: [1min, 15min, daily] # Reverted to simple list
    start_date: '2001-01-01'

  - symbol: AAPL
    description: Apple Inc.
    exchange: NASDAQ
    calendar: NASDAQ # Added calendar
    type: Stock
    default_source: tradestation
    default_raw_table: market_data
    frequencies: [daily] # Reverted to simple list
    start_date: '2001-01-01'

  - symbol: GS
    description: Goldman Sachs Group Inc.
    exchange: NYSE
    calendar: NYSE # Added calendar
    type: Stock
    default_source: tradestation
    default_raw_table: market_data
    frequencies: [daily] # Reverted to simple list
    start_date: '2001-01-01'


settings:
  data_frequencies:
    - interval: 15
      name: 15min
      unit: minute
    - interval: 1
      name: daily
      unit: day
  default_start_date: '2004-03-26'
