futures:
- base_symbol: ES
  symbol: ESH03
  update_frequency: daily
- base_symbol: ES
  symbol: ESM03
  update_frequency: daily
- base_symbol: ES
  symbol: ESU03
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ03
  update_frequency: daily
- base_symbol: ES
  symbol: ESH04
  update_frequency: daily
- base_symbol: ES
  symbol: ESM04
  update_frequency: daily
- base_symbol: ES
  symbol: ESU04
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ04
  update_frequency: daily
- base_symbol: ES
  symbol: ESH05
  update_frequency: daily
- base_symbol: ES
  symbol: ESM05
  update_frequency: daily
- base_symbol: ES
  symbol: ESU05
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ05
  update_frequency: daily
- base_symbol: ES
  symbol: ESH06
  update_frequency: daily
- base_symbol: ES
  symbol: ESM06
  update_frequency: daily
- base_symbol: ES
  symbol: ESU06
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ06
  update_frequency: daily
- base_symbol: ES
  symbol: ESH07
  update_frequency: daily
- base_symbol: ES
  symbol: ESM07
  update_frequency: daily
- base_symbol: ES
  symbol: ESU07
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ07
  update_frequency: daily
- base_symbol: ES
  symbol: ESH08
  update_frequency: daily
- base_symbol: ES
  symbol: ESM08
  update_frequency: daily
- base_symbol: ES
  symbol: ESU08
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ08
  update_frequency: daily
- base_symbol: ES
  symbol: ESH09
  update_frequency: daily
- base_symbol: ES
  symbol: ESM09
  update_frequency: daily
- base_symbol: ES
  symbol: ESU09
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ09
  update_frequency: daily
- base_symbol: ES
  symbol: ESH10
  update_frequency: daily
- base_symbol: ES
  symbol: ESM10
  update_frequency: daily
- base_symbol: ES
  symbol: ESU10
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ10
  update_frequency: daily
- base_symbol: ES
  symbol: ESH11
  update_frequency: daily
- base_symbol: ES
  symbol: ESM11
  update_frequency: daily
- base_symbol: ES
  symbol: ESU11
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ11
  update_frequency: daily
- base_symbol: ES
  symbol: ESH12
  update_frequency: daily
- base_symbol: ES
  symbol: ESM12
  update_frequency: daily
- base_symbol: ES
  symbol: ESU12
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ12
  update_frequency: daily
- base_symbol: ES
  symbol: ESH13
  update_frequency: daily
- base_symbol: ES
  symbol: ESM13
  update_frequency: daily
- base_symbol: ES
  symbol: ESU13
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ13
  update_frequency: daily
- base_symbol: ES
  symbol: ESH14
  update_frequency: daily
- base_symbol: ES
  symbol: ESM14
  update_frequency: daily
- base_symbol: ES
  symbol: ESU14
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ14
  update_frequency: daily
- base_symbol: ES
  symbol: ESH15
  update_frequency: daily
- base_symbol: ES
  symbol: ESM15
  update_frequency: daily
- base_symbol: ES
  symbol: ESU15
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ15
  update_frequency: daily
- base_symbol: ES
  symbol: ESH16
  update_frequency: daily
- base_symbol: ES
  symbol: ESM16
  update_frequency: daily
- base_symbol: ES
  symbol: ESU16
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ16
  update_frequency: daily
- base_symbol: ES
  symbol: ESH17
  update_frequency: daily
- base_symbol: ES
  symbol: ESM17
  update_frequency: daily
- base_symbol: ES
  symbol: ESU17
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ17
  update_frequency: daily
- base_symbol: ES
  symbol: ESH18
  update_frequency: daily
- base_symbol: ES
  symbol: ESM18
  update_frequency: daily
- base_symbol: ES
  symbol: ESU18
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ18
  update_frequency: daily
- base_symbol: ES
  symbol: ESH19
  update_frequency: daily
- base_symbol: ES
  symbol: ESM19
  update_frequency: daily
- base_symbol: ES
  symbol: ESU19
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ19
  update_frequency: daily
- base_symbol: ES
  symbol: ESH20
  update_frequency: daily
- base_symbol: ES
  symbol: ESM20
  update_frequency: daily
- base_symbol: ES
  symbol: ESU20
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ20
  update_frequency: daily
- base_symbol: ES
  symbol: ESH21
  update_frequency: daily
- base_symbol: ES
  symbol: ESM21
  update_frequency: daily
- base_symbol: ES
  symbol: ESU21
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ21
  update_frequency: daily
- base_symbol: ES
  symbol: ESH22
  update_frequency: daily
- base_symbol: ES
  symbol: ESM22
  update_frequency: daily
- base_symbol: ES
  symbol: ESU22
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ22
  update_frequency: daily
- base_symbol: ES
  symbol: ESH23
  update_frequency: daily
- base_symbol: ES
  symbol: ESM23
  update_frequency: daily
- base_symbol: ES
  symbol: ESU23
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ23
  update_frequency: daily
- base_symbol: ES
  symbol: ESH24
  update_frequency: daily
- base_symbol: ES
  symbol: ESM24
  update_frequency: daily
- base_symbol: ES
  symbol: ESU24
  update_frequency: daily
- base_symbol: ES
  symbol: ESZ24
  update_frequency: daily
- base_symbol: ES
  symbol: ESH25
  update_frequency: daily
settings:
  default_start_date: '2003-01-01'
  default_update_frequency: daily
