equities:
  - symbol: SPY
    description: SPDR S&P 500 ETF
    exchange: NYSE
    type: ETF
    frequencies:
      - 1min
      - 15min
      - daily
  - symbol: QQQ
    description: Invesco QQQ Trust
    exchange: NASDAQ
    type: ETF
    frequencies:
      - 1min
      - 15min
      - daily
  - symbol: AAPL
    description: Apple Inc.
    exchange: NASDAQ
    type: Stock
    frequencies:
      - daily
  - symbol: MSFT
    description: Microsoft Corporation
    exchange: NASDAQ
    type: Stock
    frequencies:
      - daily
  - symbol: GS
    description: Goldman Sachs Group Inc.
    exchange: NYSE
    type: Stock
    frequencies:
      - daily

futures:
  - base_symbol: ES
    calendar: US
    description: E-mini S&P 500 Futures
    exchange: CME
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - H
        - M
        - U
        - Z
      start_month: 1
      start_year: 3
    num_active_contracts: 4

  - base_symbol: NQ
    calendar: US
    description: E-mini NASDAQ-100 Futures
    exchange: CME
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - H
        - M
        - U
        - Z
      start_month: 1
      start_year: 3
    num_active_contracts: 4

  - base_symbol: CL
    calendar: US
    description: Crude Oil Futures
    exchange: NYMEX
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - F
        - G
        - H
        - J
        - K
        - M
        - N
        - Q
        - U
        - V
        - X
        - Z
      start_month: 1
      start_year: 4
    num_active_contracts: 12

  - base_symbol: GC
    calendar: US
    description: Gold Futures
    exchange: COMEX
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - G
        - J
        - M
        - Q
        - V
        - Z
      start_month: 1
      start_year: 4
    num_active_contracts: 6

  - base_symbol: VX
    calendar: US
    description: VX Futures
    exchange: CME
    frequencies:
      - 1min
      - 15min
      - daily
    historical_contracts:
      patterns:
        - H
        - M
        - U
        - Z
      start_month: 1
      start_year: 5
    num_active_contracts: 4

settings:
  data_frequencies:
    - interval: 1
      name: 1min
      unit: minute
    - interval: 15
      name: 15min
      unit: minute
    - interval: 1
      name: daily
      unit: day
  default_start_date: '2003-01-01'
  holiday_calendars:
    US:
      holidays:
        - name: New Year's Day
          month: 1
          day: 1
          observance: nearest_weekday
        - name: Martin Luther King Jr. Day
          month: 1
          day: 3
          observance: monday
        - name: Presidents Day
          month: 2
          day: 3
          observance: monday
        - name: Good Friday
          observance: easter_friday
        - name: Memorial Day
          month: 5
          day: -1
          observance: monday
        - name: Juneteenth
          month: 6
          day: 19
          observance: nearest_weekday
        - name: Independence Day
          month: 7
          day: 4
          observance: nearest_weekday
        - name: Labor Day
          month: 9
          day: 1
          observance: monday
        - name: Thanksgiving
          month: 11
          day: 4
          observance: thursday
        - name: Christmas
          month: 12
          day: 25
          observance: nearest_weekday
      rules:
        - name: weekend
          days: [5, 6]  # Friday and Saturday
        - name: pre_holiday
          days_before: 1
        - name: post_holiday
          days_after: 1
